# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"
settings = YAML.load_file "settings.yaml"

IP_SECTIONS = settings["network"]["control_ip"].match(/^([0-9.]+\.)([^.]+)$/)
# First 3 octets including the trailing dot:
IP_NW = IP_SECTIONS.captures[0]
# Last octet excluding all dots:
IP_START = Integer(IP_SECTIONS.captures[1])

Vagrant.configure("2") do |config|
    config.vm.provision "shell", env: { "IP_NW" => IP_NW, "IP_START" => IP_START }, inline: <<-SHELL
#   sudo dnf update -y
    echo "$IP_NW$((IP_START)) master-node" >> /etc/hosts
      for i in `seq 1 ${NUM_WORKER_NODES}`; do
        echo "$IP_NW$((IP_START+i)) worker-node0${i}" >> /etc/hosts
      done
    SHELL

    #config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", create: true
    #config.ssh.private_key_path = "C:/Users/deepu/.ssh/id_rsa"
    config.ssh.insert_key = false
    config.vm.box = "generic/centos9s"
    config.vm.box_check_update = true

    
    config.vm.define "centos" do |master|

        master.vm.network "private_network", ip: settings["network"]["control_ip"]
            if settings["shared_folders"]
            settings["shared_folders"].each do |shared_folder|
                master.vm.synced_folder shared_folder["host_path"], shared_folder["vm_path"]
            end
        end
        
        #master.vm.network "private_network", ip: 1
        #centos.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "Wi-Fi"

        master.vm.provider "virtualbox" do |vb|
            vb.cpus = settings["nodes"]["control"]["cpu"]
            vb.memory = settings["nodes"]["control"]["memory"]
            if settings["cluster_name"] and settings["cluster_name"] != ""
            vb.customize ["modifyvm", :id, "--groups", ("/" + settings["cluster_name"])]
            end
        end
        
        master.vm.provision "shell",
        env: {
            "DNS_SERVERS" => settings["network"]["dns_servers"].join(" "),
            "ENVIRONMENT" => settings["environment"],
            "ANSIBLE" => settings["software"]["ansible"]
            #,"OS" => settings["software"]["os"]
        },
        path: "scripts/common.sh"

        master.vm.provision "shell",
        path: "scripts/zsh.sh"
        
    end

end